dist: xenial   # required for Python >= 3.7
language: python
python:
    - "3.7"

services:
    - docker

before_script: pip install docker-compose

env:
    - WEBSERVER_PORT=8012
    - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION=AWS_DEFAULT_REGION

script:
  - cd .docker && docker-compose run honeypie_webserver sh -c "pytest && flake8"
